---
#Namespace for provisioner
apiVersion: v1
kind: Namespace
metadata:
  name: {{ namespace_name }}
  labels:
    name: {{ namespace_name }}

#Cluster role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    authorization.openshift.io/system-only: "true"
    openshift.io/reconcile-protect: "false"
  name: system:{{ clusterrole_name }}
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    attributeRestrictions: null
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - storage.k8s.io
    attributeRestrictions: null
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    attributeRestrictions: null
    resources:
      - events
    verbs:
      - create
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    attributeRestrictions: null
    resources:
      - endpoints
    verbs:
      - get
      - create
      - list
      - patch
      - update
      - watch

---
##Cluster role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ rolebinding_name }}
roleRef:
  kind: ClusterRole
  name: system:{{ clusterrole_name }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ namespace_name }}


