---
apiVersion: v1
kind: Secret
metadata:
  name: {{ dsm_credentials_secretname }}
  namespace: {{ namespace_name }}
type: Opaque
data:
  username: {{ dsm_username | b64encode }}
  password: {{ dsm_password | b64encode  }}